name: Validate HTML

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Validate HTML files
        run: htmlhint index.html

